### ISSUE TITLE
Reopening  56: res.write not sending chunks until res.end() is called

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [expressjs/compression#103]
This is still a issue with Node.JS using 7.3.0

**Comment by dougwilson** [comment]
Please provide full code and instructions on how to reproduce, otherwise I have no idea what I'm supposed to do here.

**Comment by dougwilson** [comment]
Reading over that issue, it was a Node.js issue / a misunderstanding of how compression works. I'll close this unless you can provide further information over what is in that issue to justify reopening.
