### ISSUE TITLE
Safari doesn't appear to be compressing.

### ISSUE THREAD

**Issue by joe-schorn** [expressjs/compression#104]
First I want to say thanks for this great library.

I'm having an issue in Safari.
I see compression working fine in Chrome and Firefox:
![screen shot 2017-01-24 at 11 23 38 am](https://cloud.githubusercontent.com/assets/7584843/22256333/6668c064-e228-11e6-9eda-536d653118f0.png)

But here's a screen shot of the same asset loading in Safari. But It doesn't seem to be compressing. 
![screen shot 2017-01-24 at 11 25 11 am](https://cloud.githubusercontent.com/assets/7584843/22256354/73648578-e228-11e6-854e-03ba196b1248.png)

I added compression to my project using the code below.
````
const app = express();
app.use(compression({ threshold: 0 }));
app.use(express.static(process.cwd() + '/public'));
app.use(morgan('dev')); 
app.use(cookieParser());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
````

The asset in the screen shots above is in the express.static directory. I'm seeing the same issue with xhr requests (they are being compressed in Chrome et al., but not in Safari.

Any help would be greatly appreciated.
Thanks!

**Comment by dougwilson** [comment]
But your Safari screenshot is showing as compressed. For example, it says "Compressed: Yes" and it shows that there was the Content-Encoding header set to gzip. What is indicating that it is not compressed?

**Comment by ondblclick** [comment]
Have kinda same issue (?). Googled a bit - people telling Safari goes crazy showing the response details because "Content-Length" header is missing (compression removes it while gzipping).

**Comment by dougwilson** [comment]
I'm still confused on what is being reported here and I don't have access to Safari. Is there an actual issue or just confusion on how to read the Safari screenshot?

**Comment by joe-schorn** [comment]
It's showing it's compressed but compression is at 1.00x. So transferred and encoded are virtually the same. For other sites with gzipping enabled, I'm typically seeing compression around 3.00x to 4.00x. So could it be compressing the files and Safari just misreporting? Is there a way to check? Thanks!

**Comment by ondblclick** [comment]
@joe-schorn yeap, One can't rely on response details without "Content-Length" header being passed in response, it seems.

Few links:
http://stackoverflow.com/questions/34657153/gzip-compression-always-1-00x-on-ios-safari
http://forums.tumult.com/t/turning-on-compression-enabling-gzip-on-your-server-to-speed-up-loading-times/4762/2
http://stackoverflow.com/questions/12369724/why-does-safari-not-accept-gzip-compression/21943693#21943693

**Comment by dougwilson** [comment]
Gotcha. I'm not familiar with Safari and do not have a Mac, so you'll need to help me out here :) I don't have anything to act on right now. Perhaps you should take a packet capture of the TCP packets and we can inspect what is actually flowing between your server and Safari browser?

**Comment by dougwilson** [comment]
Thanks, @ondblclick reading there it looks like it is just a bug in Safari for reporting that compression ratio: It compares the compressed size sent to only the content-length header, defaulting to 1x when there is none instead of correctly comparing it to the uncompressed size like the other browsers do.

**Comment by joe-schorn** [comment]
Thanks @dougwilson and @ondblclick for all your help.
