### ISSUE TITLE
Compression not working in production (Heroku)

### ISSUE THREAD

**Issue by bookercodes** [expressjs/compression#109]
In my application, I have the following code:

```js
app.use(compression())
app.use('/public', express.static('public', { maxAge: 31557600}))
````

When I run the program locally (with `NODE_ENV=production`) `/public/bundle.js` is compressed and I can see the `gzip` header value in Chrome. When I deploy the program to Heroku, despite the code **definitely** being run (I tested with trace statements and by inspecting the code on the Heroku server), `/public/bundle.js` is **not** compressed and the header value is absent.

I have double-checked that the code has been deployed correctly, and that there is not a caching problem. I am using the latest version of `compression`.

From what I've read, Heroku isn't interfering with the application or response headers.

Any thoughts?

**Comment by dougwilson** [comment]
Hi @bookercodes I really don't have any thoughts, unfortunately. Have you debugged through the code on Heroku to see what is happening? If so, can you provide any information that would help me make a code change to the module?

**Comment by dougwilson** [comment]
I'm going to close this since I never heard back.

**Comment by akrueger** [comment]
I am unable to get compression working locally or on heroku. I didn't change my "NODE_ENV" to production as I didn't see anywhere that compression only activated with that flag.

I'm using:

```
"compression": "^1.7.2",
"express": "^4.16.3"
```

```
const express = require('express')
const helmet = require('helmet')
const compression = require('compression')
const path = require('path')
const http = require('http')
const massive = require('massive')
const parseDbConnectionString = require('pg-connection-string').parse

const app = express()

const environment = app.get('env')

const port = process.env.PORT || '3001'
app.set('port', port)

// Security
app.use(
  helmet({
    expectCt: true,
    dnsPrefetchControl: true,
    frameguard: true,
    hidePoweredBy: true,
    hpkp: {
      maxAge: 7776000,
      sha256s: ['AbCdEf123=', 'ZyXwVu456=']
    },
    hsts: {
      maxAge: 31536000,
      includeSubDomains: true,
      preload: true
    },
    ieNoOpen: true,
    noCache: true,
    noSniff: true,
    referrerPolicy: true,
    xssFilter: true
  })
)

// Gzip
app.use(compression())

// Request / Response parsers
app.use(express.json())
app.use(express.urlencoded({ extended: false }))

// Angular DIST output folder
app.use(express.static(path.join(__dirname, '../dist/next-game')))

// REST API endpoints
const api = require('./api/root')
app.use('/api', api)

// Fall-through: send all other requests to the Angular app
app.get('*', (request, response) => {
  response.sendFile(path.join(__dirname, '../dist/next-game/index.html'))
})
```

**Comment by cythilya** [comment]
I have the same issue, too.

package.json

```
"compression": "^1.7.3",
"express": "4.16.2",
```

server.js

```
 const server = express();
 server.use(compression());
```
