### ISSUE TITLE
What's the minimum size for a response to be compressed?

### ISSUE THREAD

**Issue by loganhuskins** [expressjs/compression#118]
It looks like compression only happens when a response is over a (very small) size limit. What's that size limit if that's the case? Is it documented anywhere? If not, I can add it for everyone.

**Comment by loganhuskins** [comment]
Must have missed it, sorry.

**Comment by dougwilson** [comment]
It's no problem at all :) I only pointed out where it was in the docs since you were asking about the docs in addition to what it was :)
