### ISSUE TITLE
Compressing large html with style and script tags

### ISSUE THREAD

**Issue by dansuhhh** [expressjs/compression#124]
`var express = require('express')`
`var compression = require('compression')`

`var app = express()`
`app.use(compression())`

`app.get('*', renderHTML)`

`function renderHTML() {`
`  res.status(200).send( { humongous HTML file with style and script tags } )`
`}`

<img width="317" alt="screen shot 2017-10-20 at 3 58 11 pm" src="https://user-images.githubusercontent.com/9451568/31839545-96080ca2-b5af-11e7-867a-a26b0ce1a64d.png">

I've followed the docs and received a response that has a content-encoding = 'gzip' flag on it. However, the size of the response is the same as when I comment out all the compression code. Gzip-checking websites also tell me that the response really isn't gzipped.

The humongous HTML content is populated after going through several other APIs and collecting a bunch of data.

Could the issue be due to the HTML response containing css and javascript that isn't being gzipped? Do I have to separate the content I'm sending?

**Comment by dougwilson** [comment]
I mean, the response looks right and all our tests pass, so not sure. Maybe something we're not testing. Can you help me reproduce your exact environment so I have something to debug through? Probably need to know all the following:

1. Version of Node.js
2. Version of this module.
3. Version of Express.js
4. The complete HTML response to actually send.
5. The exact methodology that you are using to determine if it's compressed or not. So far to date all the issues like this that were resolved has been bad methodology, so being able to precisely reproduce your exact methodology is very important to figure out what is wrong here.

**Comment by dansuhhh** [comment]
Node 6.3.1
Compression 1.6.2
Express 4.15.2

[HTML response](https://codeshare.io/2BgwAp)

For validation, I am:
1) Checking for the Content-Encoding in the response headers
2) Checking with gzip-checking websites
3) Comparing file size with/without the compression module

**Comment by dougwilson** [comment]
Thanks! I still cannot reproduce your issue. Let me know what the next steps should be here.

**Comment by dougwilson** [comment]
Right now you're able to reproduce the issue to debug through the code to figure out what is wrong. I would love to be able to do so, but need to reproduce the issue.  You still didn't really detail exactly your method, so I may be doing something different. I ca  think of one of these as being the be next step:

1. Provide a PR with a fix.
2. Provide a PR with a test case demonstrating the issue.
3. Provide the exact request to make to the server that doesn't result in compression (the request and all it's headers is part of the protocol to determine if the response is compressed).
4. Provide a packet capture of the http stream where it is not compressed.

**Comment by dansuhhh** [comment]
http://qa.hoichoi.tv/
The issue at hand is the call for the document, measuring at 209KB. According to sites like https://checkgzipcompression.com/, it should be measuring down to 36 kb.

**Comment by dougwilson** [comment]
What is thr exact HTTP call those sites are making so I can replicate it and debug?

**Comment by dougwilson** [comment]
Please provide one of the items requested in https://github.com/expressjs/compression/issues/124#issuecomment-338323715

Or if you have a different idea, please outline exactly the steps you think I should take to fix this, otherwise I need you to provide one of those 4 items.

**Comment by dansuhhh** [comment]
I've replicated the issue in a small Node app [here](https://codeshare.io/aVjp0Qrl)

**Comment by dansuhhh** [comment]
I've recreated the issue in an example Node app [here](https://codeshare.io/aVjp0Q)

**Comment by dougwilson** [comment]
Thanks, @dansuhhh ! Can you provide me with the exact steps to reproduce? I just ran that locally and opened in Chrome and sure enough it was compressed just fine.

**Comment by dansuhhh** [comment]
Hm, interesting. I am simply running the script locally as well. 
<img width="919" alt="screen shot 2017-11-03 at 3 39 33 pm" src="https://user-images.githubusercontent.com/9451568/32392763-441aae0a-c0ad-11e7-81d0-ab770e7b582f.png">
The response size is 311kb with and without compression

**Comment by dougwilson** [comment]
If `Content-Encoding` is `gzip`, then it is compressed. Chrome's _size_ column is bugged in that if a response is `Transfer-Encoded: chunked` it will show the _decompressed_ size there instead of what was over the network. Use Wireshark to measure what was actually going over the network, please.

**Comment by dougwilson** [comment]
The uncompressed size is 318255 bytes but if you look at the network traffic over Wireshark, you'll see the server is sending the binary gzip and that it's only 43533 bytes.

**Comment by dansuhhh** [comment]
Wow, thanks alot! We just reviewed the network on Charles as well. Much appreciated, Doug.
