### ISSUE TITLE
Can I write custom logging for compression?

### ISSUE THREAD

**Issue by theonlygusti** [expressjs/compression#125]
Setting `DEBUG=compression` environment variable lets me see what compression's up to.

How can I capture this info inside my app and log it using my own logger?

**Comment by dougwilson** [comment]
Hi @theonlygusti the debugging messages this module produces uses the `debug` module, which provides a hook mechanism if you want to redirect them to your own custom logger: https://github.com/visionmedia/debug/blob/2.x/README.md#output-streams

If you also don't want to just log all the debug output and only want certain types of logs, I'm sure there is a way to do that, but would just need to understand better what you want to log to provide another tip besides the above to just redirect the `debug` output.
