### ISSUE TITLE
Question: What's the use of this plugin?

### ISSUE THREAD

**Issue by Vadorequest** [expressjs/compression#133]
This is probably a beginner question, but it's not really clear from the README what are the advantages (pros/cons) of using compression.

I guess it compress (yeah!) data sent back from the server (how? into what format by default? zip?) and somehow makes it smaller so the transfer is faster. (I guess that's the point of compression, making things travel faster)

Does that has any effect on SEO or Open Graph?

**Comment by paOol** [comment]
it's cheaper on your server costs.

a user spamming an api = CPU cycles.
a user downloading a big image = bandwidth.

when you combine caching and compression, its cheaper to optimize in code than buying more hardware.

if you serve a billion requests, it might reduce the workload of your server by a huge %.

**Comment by dougwilson** [comment]
@Vadorequest let us know if you have any further questions not answered above 👍

**Comment by Vadorequest** [comment]
@dougwilson thanks! I was waiting for more answers to see if there were any other pros/cons ;)

But I guess that's it then ;)

**Comment by dougwilson** [comment]
Ah, gotcha. Because this module just implements HTTP compression, you are likely to get more answers asking why you would in general use HTTP compression on a site like Stackoverflow if you haven't tried that yet :+1:

**Comment by Enalmada** [comment]
It in my understanding that you should only use compression if you are not behind a proxy that does it for you.  AWS lambda has a gzip setting that I believe you should set to 1400 which seems to be the general recommendation.
