### ISSUE TITLE
 Are you misunderstanding npm's public setting?

### ISSUE THREAD

**Issue by rorono** [expressjs/compression#143]
Recently, you can not download compression from npm or yarn.
I ran the install command as documented in the `compression` documentation.
However, it could not be installed with a 500 error.

So, I doubt that **compression's setting to npm is incorrect.**

This problem affects all packages on which this package depends.
- Example: `webpack-dev-server` etc.

Circumstances
-----
1. `webpack-dev-server` could not be installed.
2. I confirmed that `compression` can not be downloaded.

Finally
-----
I can confirm the problem that I faced from the issue below.

https://github.com/webpack/webpack-dev-server/issues/1423

**Comment by dougwilson** [comment]
I'm not sure I understand what the issue is. I haven't changed anything in months and a 500 from npm sounds like a npm registry error, not something I can address as a module author.

If you can provide clear steps on specifically what action(s) I need to take I can reopen.
