### ISSUE TITLE
Say in the documentation, very near the top that it's for node Express

### ISSUE THREAD

**Issue by metabench** [expressjs/compression#145]
This way it would save time for those who are not looking for Express middleware but are interested in compression middleware.

If this can be used outside of Express, then that should have some documentation.

**Comment by dougwilson** [comment]
It is not specific to Express. None of our tests even use Express. I can add docs for how to use it in something else. What are you trying to use it in?

**Comment by dougwilson** [comment]
> Say in the documentation, very near the top that it's for node Express

It's not just for Express which is why it doesn't say that.

**Comment by metabench** [comment]
I was trying to use it in a component that's summarised by needing to compress buffers that get sent to HTTP responses in node.

I only had a very quick superficial look at the project, but I got the impression from the code samples that it was only for Express, seeing non-express examples would prevent that incorrect impression from forming.

**Comment by metabench** [comment]
I glossed over exactly where I was planning on using it because getting into that brings up loads more complexity, but in case you are interested, here it is: https://github.com/metabench/jsgui3/blob/master/server/website-javascript-resource.js

I'm writing a full-stack framework that integrates express-like serving (different API though). A while ago I looked into Express and saw it stores the routes in an array rather than a tree (meaning slower routing of sites with many pages). Do you mind telling me if that's still the case?

It would be great to use bits and pieces from the Express and Koa projects if they are encapsulated in a suitable way and do useful tasks.

Compression is one such area where express or express-compatible middleware would be useful for jsgui. I've got that framework doing some useful things now. It basically works.
