### ISSUE TITLE
Compression not working in Heroku

### ISSUE THREAD

**Issue by cythilya** [expressjs/compression#146]
I have gzip when I run "yarn run dev" in local, but after I run "heroku local" or deploy my app to Heroku, gzip is gone. Below are my code snippet.

package.json

```
"compression": "^1.7.3",
"express": "4.16.2",
```

server.js

```
const server = express();
server.use(compression());
```

or  view my [repo](https://github.com/cythilya/dotch_food_v2/tree/heroku) and [demo](https://dotch-food.herokuapp.com/).

**Comment by dougwilson** [comment]
Can you provide a specific example URL to call so I can test the same one (since there are lots of URLs in that app)?

**Comment by cythilya** [comment]
Please view this [url](https://dotch-food.herokuapp.com/_next/e38ae54f-382e-4377-93a8-b87afdf51771/page/_app.js). 

When I run in local "yarn run dev"

<img width="1088" alt="2018-09-12 10 09 28" src="https://user-images.githubusercontent.com/3736018/45397789-336c5780-b674-11e8-9d3a-bbff3a11d310.png">

After I deploy my app to Heroku

<img width="1088" alt="2018-09-12 10 09 28" src="https://user-images.githubusercontent.com/3736018/45397791-35361b00-b674-11e8-802c-887638f6aebb.png">

**Comment by dougwilson** [comment]
Yea, I'm also not seeing it as compressed. Is there a way to attach a debugger into the running code on Heroku to see what is happening?

**Comment by Avcajaraville** [comment]
Same here, my assets are not being compressed and they are reported by google page speed as not compressed :)

Thanks

**Comment by Avcajaraville** [comment]
Actually, this problem is not related to Heroku, as in local the same results are outputted on the network tab.

So, its reproducible also in local environments.

**Comment by dougwilson** [comment]
Hi @Avcajaraville sorry to hear you're having the same issue. I would live to debug through the issue to get to a resolution. Can you provide code and steps to reproduce so I can examine?

**Comment by Avcajaraville** [comment]
@dougwilson I just set a minimum gist that reproduces the issue [here](https://gist.github.com/Avcajaraville/121d098589b018b2ae103750d8b39887#file-index-hbs)

As you can see, the css file is being gzip, while the svg is not:
![captura de pantalla 2018-09-13 18 58 38](https://user-images.githubusercontent.com/2271201/45503476-35730b00-b787-11e8-8108-d97f9226f243.png)
![captura de pantalla 2018-09-13 18 58 50](https://user-images.githubusercontent.com/2271201/45503474-35730b00-b787-11e8-8175-1cd4b942a667.png)

**Comment by dougwilson** [comment]
Ah, thanks @Avcajaraville ! This is because the SVG file in your example does not exceed the default value for the `threshold` option (https://github.com/expressjs/compression#threshold) which is 1kb. Responses below that threshold size are not compressed. You can lower the threadshold if you need it compressed 👍

**Comment by Avcajaraville** [comment]
Thanks a lot @dougwilson that was a super useful and quick answer :)

This is also the reason why this is not working for @cythilya.

We should read the docs more carefully :)

Really nice response time and great job with this module !!

**Comment by dougwilson** [comment]
It's no problem! Happy to help.
