### ISSUE TITLE
Setting Vary header although caching is disabled 

### ISSUE THREAD

**Issue by nolimitdev** [expressjs/compression#151]
I think that setting "Vary" header is useless and misleading when cache control is totally disabled by "no-cache" directive in "Cache-Control" header. Is it possible to remove it in this case? This module sets by default "Vary: Accept-Encoding".

**Comment by dougwilson** [comment]
The Vary header is set when this module makes a decision about the response by looking at the Accept-Encoding header.

Vary is not for use exclusive for caching and it's value is a generic signal. You can read more in the specification for the header: https://tools.ietf.org/html/rfc7231#section-7.1.4
