### ISSUE TITLE
Question: Why this middleware

### ISSUE THREAD

**Issue by greatbody** [expressjs/compression#161]
Hi as far as I know, Nginx can handle the compression job, and it's written in c, so it's supposed 
 to be faster than this node.js module.

I know that when we use express without nginx, this could be an option, but why not nginx but express with compression?

Thank you so much.

**Comment by dougwilson** [comment]
Use NGINX if you can do so.

**Comment by dougwilson** [comment]
http://expressjs.com/en/advanced/best-practice-performance.html#use-gzip-compression
