### ISSUE TITLE
Corrupted compressed .js-files for Mac OS / Safari -clients

### ISSUE THREAD

**Issue by ICarryTheDustOfAJourney** [expressjs/compression#162]
Using compression 1.7.4 with express 4.17.1 on Node 10.16.3. on an up-to-date Linux OS. Works fine with all other clients, but not when using Safari on Mac OS. Chrome and FF on Mac OS are no problem, Safari on iOS works too.

Static .js-files get terminated in the middle, leading to invalid scripts. Disabling compression "solves" the problem. Can't believe this is a Safari weakness.

Not using any fancy options.
` expressApp.use(compression());`

Packages used
`"dependencies": {
    "body-parser": "^1.19.0",
    "compression": "^1.7.4",
    "express": "^4.17.1",
    "extend": "^3.0.2",
    "fs-extra": "^8.0.0",
    "mailparser": "^2.7.1",
    "mongodb": "^2.2.36",
    "multer": "^1.4.2",
    "node-7z": "^1.0.0",
    "nodemailer": "^6.0.0",
    "request": "^2.88.0",
    "spdy": "^4.0.0",
    "wl-msg-reader": "^0.2.0",
    "ws": "^3.3.3"
  }`

**Comment by dougwilson** [comment]
I don't have a Mac so I'm not sue I will be able to troubleshoot this for you, unfortunately. Would you be willing to dig into the underlying cause?

**Comment by ICarryTheDustOfAJourney** [comment]
Thx! How can I support you?
Here is a related [post](https://stackoverflow.com/questions/53270445/) on SO

**Comment by dougwilson** [comment]
Gettng a packet capture of the traffic at the server and the same traffic at the client would help me see if (1) there are any obvious issues with the response from a standards pov and (2) if the response was altered between those two points.

**Comment by ICarryTheDustOfAJourney** [comment]
I'll try to get a capture, but that may take a while. What format/tool?
Not sure how I can get a tool on Mac OS side, I'm not a Mac user either.

**Comment by dougwilson** [comment]
I am about to go to work, so won't likely be able to respond for the rest of the day anyhow. The tool you use doesn't matter; whatever works on that OS. Ideally a pcap file is good, but if there is a different formar you are restricted to, just upload that and we can work though with that.

**Comment by ICarryTheDustOfAJourney** [comment]
It occurs only in combination with http2 (https:) using spdy. Http works fine with compression. Is an TLS-encripted capture of any use for you? If not, what else?

I'm new to this level of debuging. Sorry when asking silly questions here.

**Comment by dougwilson** [comment]
So I think you are on track to narrow down on what the issue could be happening from. A packet capture can be used even if it is encrypted, but just needs to be decrypted. Decrypting requires having the symmetric key that was exchanged or just having a capture of the ssl handshake and the private key from the server.

Of course if that is a real server with a real cert, don't share the private key, but you could even decrypt locally and then share the decrypted capture, for instance. The Wireshark tools makes it pretty straight forward, for example.

**Comment by ICarryTheDustOfAJourney** [comment]
OK, I installed wireshark and have to find out, how to decrypt using the key I have.

**Comment by ICarryTheDustOfAJourney** [comment]
After throwing some hours against it, I'm giving up for the moment:
I followed https://wiki.wireshark.org/TLS?action=show&redirect=SSL#TLS_Decryption
- I'm not able to decrypt using a  SSLKEYLOGFILE, Safari's doesn't seem to support that.
- I'm not able to decrypt using the the server's  private key .

So I'll live for the moment with Safari on Mac OS users not compressing and keep recommending Chrome & FF, if compression matters. Thx for your time.

**Comment by ryhinchey** [comment]
> Update: It works when using module https instead of spdy. Could also be a spdy issue. Can't use HTTP2 for the moment since it is seems to be no drop-in replacement for spdy/https.

@ICarryTheDustOfAJourney I did a little digging and came across this post from Apple:
https://webkit.org/blog/8569/removing-legacy-spdy-protocol-support/

What version of macOS and iOS were/are you testing on?  I wonder if this issue could be replicated in recent versions of these browsers?  With SPDY being deprecated for some time, it's certainly possible you hit a bug that doesn't exist in a newer version of Safari.

If you have a minimal reproducible example, I'd be happy to test it as well.

**Comment by ryhinchey** [comment]
Closing this issue as I don't think there's anything we can do in compression for this at the moment and is probably an issue related to spdy and safari.  as always, feel free to re-open if there's a reproducible issue here.
