### ISSUE TITLE
Is compression working when node server is running on a container?

### ISSUE THREAD

**Issue by DanDubinsky** [expressjs/compression#163]
We have the package working fine on local development machines (Mac Catalina), but it doesn't seem to compress anything when we deploy on Kubernetes in a container.  The base container we are using is the standard node 10.16.3 from Docker Hub, but that's a rather minimal Linux distro and I'm wondering if there are some OS dependencies that we need to install.

**Comment by dougwilson** [comment]
I haven't had issues with this module inside kubernetes, personally, and there are no dependencies to install outside the module.

**Comment by jonchurch** [comment]
Closing as no response.
