### ISSUE TITLE
middleware fails when the request has more than 1 values for accept-encoding header

### ISSUE THREAD

**Issue by rishisharma08** [expressjs/compression#165]
i have something like this to pass multiple headers

`request.setHeader('accept-encoding', ['something', 'gzip']);`

this is valid in nodejs. but get an error form compression:

"message":"accept.split is not a function"

**Comment by dougwilson** [comment]
Hi @rishisharma08 thanks for the report. I cannot seem to replicate the issue. Can you provide more specific instructions on how, exactly, to reproduce the error? Or maybe the entire stack trace for the error?

**Comment by jonchurch** [comment]
Closing as no reproduction
