### ISSUE TITLE
change Transfer-encoding

### ISSUE THREAD

**Issue by khaledosama999** [expressjs/compression#168]
Im using the middleware for compressing JSON ajax responses is there anyway to change the Transfer-encoding header value from chunked to gzip for example so i can display the Content-Length header ?

**Comment by dougwilson** [comment]
Afaik no web browser supports gzip in transfer-encodong, only in content-encoding.

That said, if you want to make a pull request with the change and testing shows it works in various web browsers and clients we will accept it.
