### ISSUE TITLE
Force size to be a minimum...

### ISSUE THREAD

**Issue by joetidee** [expressjs/compression#171]
We currently use this library on a server that, when asked to render the page, will send down an initial response (560bytes) followed by a node stream of the rest of the page once the page has been generated and is ready to send.
We use a proxy server and this has a minimum buffer size of 8kb. When it reaches this size it will flush the contents to the browser. Therefore, that first chunk of data needs to reach the 8kb threshold in order for the proxy to flush it. Is there a way pad this initial response to the threshold size?

**Comment by dougwilson** [comment]
There is no such option in this module. I don't think the Node.js gzip API itself provides that possibility, though, which would be necessary to add such to this module.

**Comment by mastermatt** [comment]
@dougwilson as I come across "question" issues that seem to be answered, my plan is to close them.
If you see anything close that could/should have more discussion, reopen the issue and I'll adjust according.
