### ISSUE TITLE
Angular Not Compressing?

### ISSUE THREAD

**Issue by jfarnsworth95** [expressjs/compression#181]
I'm certain I'm doing something wrong, but I'm not getting errors and the main-es2015 file (along with all the other files) are not marked as compressed in the chrome dev console. The app still works fine otherwise.

In the server file that creates the express app obj:
```const compression = require('compression');
const express = require('express');
const path = require('path');
const app = express();
require('dotenv').config();

console.log(process.env.FRONTEND_SERVER_PORT);
app.use(compression())

app.use(express.static(path.join(__dirname, 'dist')));

app.get('/*', function(req, res) {
    res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(process.env.FRONTEND_SERVER_PORT);
```

Package.json:
```{
    ...
    },
    "private": true,
    "dependencies": {
		...
        "compression": "1.7.4",
        ...
    },
	...
}
```

Any idea what I've implemented incorrectly here, or what other info is needed to debug this? The lack of any error is really throwing me off.

**Comment by dougwilson** [comment]
Hi @jfarnsworth95 sorry you are having trouble. This module does not throw any errors, as sending a non compressed response is not an error.

I don't see anything wrong in your example code, but there isn't enough information for me to really look any deeper. If you would like us to look further, please provide a complete app we can run and provide the details of the http request you are making to said server that you are expecting to get a compressed reaponse for.

**Comment by jfarnsworth95** [comment]
Given the nature of the app I'm working with, I don't think I can provide more than I've already shown.
I understand this means there's nothing to be done, so I'm sorry for taking up your time.
