### ISSUE TITLE
compression not working json payload

### ISSUE THREAD

**Issue by juber-ivre** [expressjs/compression#182]
I'm using compression module but it doesn't seem to have any effect on my payload.

The way I had it setup it' pretty standard, a middleware to compress everything. Any suggestions please.

compression v1.7.4
express v4.17.3
node v16.14.0
sequelize v6.16.1

The screenshot shows the size of the payload with or without compression module.

![image](https://user-images.githubusercontent.com/48788224/161026032-aa781127-8c05-4c93-84ff-fdd098148c65.png)

**Comment by juber-ivre** [comment]
I know this has been tagged as a question but perhaps it should be dealt as a bug.

I was trying a very simplified version, if that worked I would know it was something else in my code so here's my setup

![image](https://user-images.githubusercontent.com/48788224/162562536-e80f74bb-48e2-4a6d-8ad8-c39b9936b41d.png)

compression v1.7.4
express v4.17.3
node v16.14.0

Here's the before and after results, no matter what I'm still getting the same 5.24mb in my response.

![image](https://user-images.githubusercontent.com/48788224/162562729-c0fe9b77-9298-4f36-86a5-0db1499375cc.png)

**Comment by dougwilson** [comment]
Hi @juber-ivre sorry you are having trouble. Though you did not provide the testdata value for your app, I made up a 5mb randome value for testing. Unfortunately I am unable to reproduce your issue and am getting a compressed response from your example app.

You are always welcome to submit a pupl request with a fix, though, as it sounds like you are saying you have identified this as a bug in this module. If you're unsure of how to make the fix, please outline where you have located the bug and/or provide a complete, reproducable example so we can try and come up with a fix for your issue.

**Comment by juber-ivre** [comment]
Thanks for your response @dougwilson. Do you think that may be a relation with versions I'm using? Perhaps you could suggest versions you have on your local? I've tried JSON and Text but both the same. I'm hitting the middleware for sure but I'd need to dig further to see why is not compressing.I'll be back with some more info.

**Comment by dougwilson** [comment]
I just used the exact versions you listed, including even the Node.js version.

**Comment by juber-ivre** [comment]
Went to another round of tests, trying a even simpler scenario but still unable to see the compression on Postman. I can see I'm hitting "shouldCompress" at all times but not getting the expected ending result.


![image](https://user-images.githubusercontent.com/48788224/162952738-3fbe4baa-1450-4ff6-a24c-b5b5c0d2c4c9.png)


![image](https://user-images.githubusercontent.com/48788224/162953006-4c301263-336c-4b1a-a7ad-6700ce90ce3b.png)

**Comment by juber-ivre** [comment]
Got to the bottom of it. Compression is working accordingly but Postman seems to have an open issue with regards compressed size, as per reference below.

On Browser you can see compressed size as well the source size.

![image](https://user-images.githubusercontent.com/48788224/163016200-6d5bced7-8a0e-4406-9c0d-1ac73bc0fb0f.png)

https://github.com/postmanlabs/postman-app-support/issues/7596
