### ISSUE TITLE
Crash when compressing characters like ū

### ISSUE THREAD

**Issue by tsukinoko-kun** [expressjs/compression#184]
I tried to compress `"Chūnin"` and this compression function crashed.
Tried to use `btoa("Chūnin")` but `btoa` doesn't support non-ASCII either.

**Comment by dougwilson** [comment]
Hi @Frank-Mayer sorry to hear that. We have tests already for strange characters and I quickly modified the test to use `Chūnin` and didn't have an issue. Can you provide the following information to help us diagnose?

Version of Node.js
Version of this module
Code to replicate the problem

Thank you!

**Comment by bjohansebas** [comment]
Hi @tsukinoko-kun, no further information has been provided on this. I’ve tried changing the tests as well and there hasn't been any error. I’ll close this for now, but if the issue persists, feel free to open this issue again.
