### ISSUE TITLE
Sending really large response sends duplicate

### ISSUE THREAD

**Issue by DaftMonk** [expressjs/compression#20]
When responding with a very large json object, a duplicate is sent along with it when using the compression middleware.

E.g. the response on my endpoint in chrome and firefox is {_id: 1212, ...... }{_id: 1212, ...... }. When I remove the compression middleware it correctly sends one object.

Original issue: https://github.com/DaftMonk/generator-angular-fullstack/issues/380

**Comment by kingcody** [comment]
@dougwilson I believe I can help reproduce the error that @DaftMonk originally had.

I added a [test](https://github.com/kingcody/compression/commit/47d8f4bfa80680db370eb12c754784568a274469) that tries to send large bodies with 'Content-Type application/json'; which [fails](https://travis-ci.org/kingcody/compression/builds/71134450) with supertest reporting that the callback was called twice.

I'm currently trying to get to the root of the issue but it might be much more apparent to someone with more expirence with the project and its libs.

**Comment by dougwilson** [comment]
Your test is failing because you never called done. You need to add done as the third argument to your last expect.

**Comment by dougwilson** [comment]
As in, you need to have your last expect like this:

    .expect(200, buf.toString(), done)

**Comment by kingcody** [comment]
@dougwilson that was actually a last minute error, my mistake. I've corrected and the issue still stands.

Thank you for your reply.

**Comment by dougwilson** [comment]
> I've corrected and the issue still stands.

What is the issue that still stands? You have only provided a link to that broken test with the broken Travis from the forgotten done argument. Are there new links you need to provide me? I don't have additional information here beyond the missing done argument in the test.

**Comment by kingcody** [comment]
> Are there new links you need to provide me?

[Updated commit](https://github.com/kingcody/compression/commit/778988d8814c9f73304273af4f6ac179ea0b9c1b)
[Updated test](https://travis-ci.org/kingcody/compression/builds/71138413)

**Comment by dougwilson** [comment]
Thanks. The error in Travis is yet another supertest error or something. I will not have access to a computer for quite a long time, so unless there is a PR you can make, I cannot promise it will be looked into anytime soon.

**Comment by dougwilson** [comment]
It's too bad that stack trace says nothing. It almost looks like the error is occurring within Node.js core itself, based on the stack trace, which is only a single entry (at least looking at Travis CI on a mobile phone).

**Comment by dougwilson** [comment]
Oh, I see the issue. The problem is that supertest is actually trying to JSON.parse the response, because of the content type. Your test is failing because of that, yet again a supertest issue. If you are going to send JSON, you need to write actual JSON to get through supertest.

**Comment by kingcody** [comment]
The actually throw is coming from [supertest/lib/test.js:169](https://github.com/visionmedia/supertest/blob/master/lib/test.js#l169)

```bash
     Uncaught TypeError: Cannot read property 'text' of undefined
      at Test.assert (/home/kingcody/git/compression/node_modules/supertest/lib/test.js:169:23)
      at Server.assert (/home/kingcody/git/compression/node_modules/supertest/lib/test.js:131:12)
      at Server.g (events.js:199:16)
      at Server.emit (events.js:104:17)
      at net.js:1419:10
      at process._tickCallback (node.js:355:11)
```

**Comment by kingcody** [comment]
Ok, I'll correct. Thank you

**Comment by dougwilson** [comment]
As an update from @kingcody for those watching here, he posted the following at https://github.com/DaftMonk/generator-angular-fullstack/issues/413#issuecomment-121740862 :

> Hmm, it would seem that connect-livereload@0.4.x was actually causing the issue; but only when used with expressjs/compression.
>
> By upgrading (npm install --save-dev connect-livereload@0.5.3) to the newest version the issue was resolved in my tests.

This would make complete sense, as I am one of the people who reported the bug to `connect-livereload` a long, long time ago. I wasn't aware people who still be using such an old version of that library still, though. The issue with `connect-livereload` was fixed back in Nov 2014.

It sounds like this issue has been settled on the use of an old, buggy `connect-livereload`, do you agree, @kingcody ? The details of the old issue can be found here: https://github.com/expressjs/cookie-session/issues/14#issuecomment-46964653 as it had the same issue with any library overwriting `res.write` like `express-session` and this module.

**Comment by dougwilson** [comment]
And to add some more specificity to the issue, you need `connect-livereload >= 0.5.0` for the fix, as it was released in 0.5.0.

**Comment by kingcody** [comment]
> this issue has been settled on the use of an old, buggy connect-livereload

@dougwilson I wanted to track it down before confirming, but that is correct. I found that the issue was fixed by https://github.com/intesso/connect-livereload/commit/8c2227b8ed04f7b3a4f4d7b79a179db348f6c133


> you need connect-livereload >= 0.5.0 for the fix

Actually `connect-livereload >= 0.4.1` solves the issue I was having.

Again, thank you so much for your help and patience (:

**Comment by dougwilson** [comment]
Oh, cool :+1: So just `connect-livereload >= 0.4.1` :)

**Comment by Awk34** [comment]
:+1:  I'm interested in what caused the problem. Do you know which issue/pr fixed it?

**Comment by dougwilson** [comment]
The link https://github.com/expressjs/cookie-session/issues/14#issuecomment-46964653 explains what in their module was causing the issue. As for what specific PR or commit in the `connect-livereload` module fixed it, you may have to ask the author to find out :) I didn't see anything obvious when looking in the commit history on their GitHub repo.

**Comment by dougwilson** [comment]
In the commit you listed in their module, I see they removed a call to the `restore` function, which is likely what fixed the issue.

**Comment by dougwilson** [comment]
Ah ha! The commit https://github.com/intesso/connect-livereload/commit/6934f2039fe42735009e6f1b50a0ab17a0c1e0fa is the real fix, for the underlying issue I outlined in `express-session` module.

**Comment by dougwilson** [comment]
The main issue was https://github.com/intesso/connect-livereload/issues/41 and the pull request was https://github.com/intesso/connect-livereload/pull/53

**Comment by Awk34** [comment]
neat, thanks!
