### ISSUE TITLE
prefer deflate only as last resort

### ISSUE THREAD

**Issue by dougwilson** [expressjs/compression#26]
Sending conforming DEFLATE responses are not accepted by any version of IE (IE 11 is current as of this writing); see some convo in #25. DEFLATE is still useful for clients that only support it and there's no real reason _not_ to support it, but may as well send gzip even if the client says it prefers deflate more, as long as the client lists that it can accept gzip.

**Comment by jonathanong** [comment]
why not just not support it and not encode it?

**Comment by dougwilson** [comment]
> vs. lying

How would this be lying? The server is allowed to negotiate just like the client.

> why not just not support it and not encode it?

I looked at requests to our APIs and there are some Java and other non-browser clients that are only accepting deflate.

**Comment by jonathanong** [comment]
oh sorry read it wrong. thought the clients were only sending `DEFLATE`. SGTM :D

**Comment by dougwilson** [comment]
But yea, I think this is the best solution for the long term support :) I'm really surprised that IE 11 _still_ doesn't work right w.r.t deflate, but LOL. I certainly don't really _want_ to add UA sniffing in here though :D
