### ISSUE TITLE
Document zlib options

### ISSUE THREAD

**Issue by ilanbiala** [expressjs/compression#28]
Based on the [zlib options](http://nodejs.org/api/zlib.html#zlib_options), it seems like there are some extra properties that can be used but aren't very well documented there either (level, memLevel, and strategy). Does it make sense to at least show which ones can be accepted?

**Comment by Fishrock123** [comment]
All options are passed to zlib. You can look up the zlib docs separately if you need to know the details. :)

Usually you wouldn't touch those things, they already default to the optimal sweet spot levels on nearly every machine.

**Comment by dougwilson** [comment]
So I had thought about doing this back at the beginning of 2014, but gave up, because I couldn't just copy Node.js docs, had to read and come up with good explanations of the stuff from the zlib man page, and have to check that those explanations actually match what Node.js is doing.

@ilanbiala if you're willing to do this, I would happily add it/accept a PR :)

**Comment by ilanbiala** [comment]
@dougwilson how explanatory do you think it should be?

**Comment by dougwilson** [comment]
> how explanatory do you think it should be?

Probably just good enough so you don't have to consult any other docs to understand what they mean, since that's what it does right now (points you to read another doc source). So like an explanation that makes sense, the type and range of values the option takes.

**Comment by hex7c0** [comment]
like this?
https://github.com/kesla/node-snappy/blob/master/benchmark/benchmark.js
`level: zlib.Z_BEST_SPEED`
`memLevel: zlib.Z_MAX_MEMLEVEL`

**Comment by hex7c0** [comment]
> Usually you wouldn't touch those things, they already default to the optimal sweet spot levels on nearly every machine.

can I suggest these zlib options as default?
https://gist.github.com/hex7c0/25165f2f4650dfe16832

**Comment by Fishrock123** [comment]
Why would we use those as defaults? Those values are not going to be worth your while. :)

Max speed will be faster, but compress way too little. Max memory is also certainly unnecessary, otherwise it would be the default.

**Comment by Fishrock123** [comment]
@hex7c0 Hmmm, benchmarks look promising though. How big is the file you are transferring?

**Comment by hex7c0** [comment]
@Fishrock123 I use @kesla's [benchmark](https://github.com/kesla/node-snappy/blob/master/benchmark/benchmark.js)
so the file is [this](https://github.com/kesla/node-snappy/blob/master/deps/snappy/snappy-1.1.2/snappy.cc) `46Kb`

from http://nodejs.org/api/zlib.html#zlib_memory_usage_tuning
> memLevel = 8 (default values)

from http://zlib.net/manual.html#Constants
> The memLevel parameter specifies how much memory should be allocated for the internal compression state. memLevel=1 uses minimum memory but is slow and reduces compression ratio; memLevel=9 uses maximum memory for optimal speed. The default value is 8. See zconf.h for total memory usage as a function of windowBits and memLevel.

with `zlib.Z_MAX_MEMLEVEL` ([maybe](https://github.com/joyent/node/blob/master/deps/zlib/zconf.h#L233-L239)) you can raise to 9

**Comment by hex7c0** [comment]
regard compression/speed
`46155 bytes no compression`
`14105 bytes default compression`
`16481 bytes zlib.Z_BEST_SPEED compression`

there isn't too much difference :) `+2376 bytes`

**Comment by ilanbiala** [comment]
@Fishrock123 do those settings make sense?

**Comment by dougwilson** [comment]
If someone wants them documented here, please see https://github.com/expressjs/compression/issues/28#issuecomment-68645901 . What I need is a specific list of the options and exactly what they do and what values they accept (and their complete value range).

**Comment by dougwilson** [comment]
This is an example of what I'm looking for: https://github.com/expressjs/compression/commit/c5b813e319e33cb5feb0237de065a25d6c3bde6b
