### ISSUE TITLE
More advanced compression "filter"

### ISSUE THREAD

**Issue by ilanbiala** [expressjs/compression#29]
Some compression libraries will lower the compression level and even stop compressing if the memory consumption gets too high, and then they will start compressing again once the system has calmed down. Is there something available like that here?

**Comment by Fishrock123** [comment]
That is zlib's concern, I believe.

**Comment by dougwilson** [comment]
The way you can do this is simply to wrap this middleware, just like any middleware.

Simple example:
```js
var compression = require('compression')
var express = require('express')

express.use(variableCompression())

function variableCompression() {
  var compressors = Object.create(null)

  return function (req, res, next) {
    if (!should_compress) { // should_compress is up to you
      next()
      return
    }

    var level = get_compression_level() // get_compression_level is up to you
    var compressor = compressors[level] || (compressors[level] = compression({level: level}))

    compressor(req, res, next)
  }
}
```

**Comment by ilanbiala** [comment]
@dougwilson thanks for the start, does zlib handle any of that, or I have to? Any ideas on how to get memory consumption percentage through node?

**Comment by dougwilson** [comment]
> does zlib handle any of that, or I have to?

I really don't know :/

> Any ideas on how to get memory consumption percentage through node?

I've never tried to do that, so I'm not sure off-hand. There is an `os.totalmem()` and `os.freemem()` in the `os` module (http://nodejs.org/api/os.html) that you could probably use.

**Comment by ilanbiala** [comment]
@dougwilson thanks for the help!

**Comment by dougwilson** [comment]
No problem :) Feel free to continue to ask follow ups on this issue, btw.
