### ISSUE TITLE
caching compressed static content

### ISSUE THREAD

**Issue by avivek** [expressjs/compression#36]
Is there a way in which when using compression on static content served using express static, the compressed content can be cached somewhere so that we can avoid the need to re-compress stuff often?

**Comment by dougwilson** [comment]
So this is a generic module that compresses all responses, including dynamic content. This module has no way to know if it's from a static file, though. There are several modules on npm that can serve compressed static content from disk if you like, but it's almost impossible to search around from a cell phone. I'm sure you'll find them, but yes, this module cannot do that.
