### ISSUE TITLE
Using compression in spdy server push

### ISSUE THREAD

**Issue by hdf** [expressjs/compression#40]
Is there any way to do this? To somehow use this middleware while pushing cached data trough spdy with push? I might be able to do the gziping of the data, but if it's large, chunking becomes a problem, and I really don't want to deal with the headers manually.

**Comment by dougwilson** [comment]
Hmm, I don't think this module works with SPDY push, though I also think no Express middleware does, either (middleware that alters the response). I'm not too familiar with SPDY push, though.

Would you be willing to post an example or even work on a PR to add this :)?

**Comment by hdf** [comment]
I could try, but I might need some pointers. Like which parts of the code to focus on. Should also figure out first how exactly we want this to work.
My current idea is something like this:
```javascript
var compress = require('compression');
var file_name = 'file.js';
var file = fs.readFileSync(file);
var compressed = compress(file_name, file);
...

  var stream = res.push('/' + file_name, compressed.headers, pushHandler);
  compressed.data.pipe(stream);
  stream.end();
```
What do you think?

**Comment by dougwilson** [comment]
That looks like a different module; this module is only an Express middleware.

**Comment by hdf** [comment]
But I would like to reuse a lot of what `compression` does, like determine, if it should be compressed at all, and what headers to set based on that. Maybe if its like this?:
```javascript
var compresser = require('compression').compresser;
var compressed = compresser(file_name, file);
```

**Comment by dougwilson** [comment]
Still no; if you extract that stuff as another generic module, we can simply use your lower-level module. The only interface this module will have an an Express middleware interface.

**Comment by hdf** [comment]
So you want me to make something, that `compression` itself will be based on? Wow, that's a big request, I'm still a newbie to this, not feeling very confident.

**Comment by dougwilson** [comment]
Right, though I did intend to do this eventually, if you don't mind waiting, and are hesitant to do it :) When I get to a computer, I do believe there may be a way to at least temporarily hack an Express middleware to manipulate a stream, though would need to know how to use SPDY push if you can provide an example.

I think you would find that implementing that extra export as a non-hack would mean rewriting the internals of this module anyway :)

**Comment by dougwilson** [comment]
> It's a bit weird, that currently we can't conveniently use compression in a push stream. Makes the whole thing kind of pointless (server pushes). Or so it feels.

I agree, but have no experience using them, so have no idea how to go about changing this or even how to make a server that does push and understand how to make a request to said server to see the result of the push, if you can teach me?

**Comment by hdf** [comment]
Currently for client side testing I'm just using the latest Firefox and Chrome, and their DevTools (ctrl+shift+i).
My current server code for push is probably pretty embarrassing, but here it is commented out:
https://github.com/hdf/clusters/blob/master/server/index.js#L109

Another idea: Is it possible, to somehow "virtually" trigger `compression`, and feed what it gives to that push function and stream?

**Comment by dougwilson** [comment]
> Another idea: Is it possible, to somehow "virtually" trigger  compression , and feed what it gives to that push function and stream?

That sounds like the "hack" I was thinking about, yes.

**Comment by hdf** [comment]
How hard would this hack be? What data is `compression` checking, and what exactly does it write? If the hack is not too complicated, or embarrassing, it might do at least until one of us does the "greater deed".

**Comment by hdf** [comment]
Ok, the browsers do support it. I have made some progress, but there are weird bugs. Like it sets compression header even when I did not tell it to. Caching problem? Or stream window gets confused? Dunno, lots of debugging await me.

**Comment by hdf** [comment]
OK, I have solved this for my self, and it is now clear, that this is not an express compression issue. It is best, if files that should be pushed are cached in a compressed state. And that is really contrary to how this module works.
