### ISSUE TITLE
threshold doesnt behave as expected if resp.writeHead is used

### ISSUE THREAD

**Issue by vsacheti** [expressjs/compression#43]
```
var compression = require('compression')
var express = require('express')

var app = express()

// compress all requests 
 app.use(compression())

app.get('/', function (req, res) {
        res.writeHead(200, {"Content-Type" : "text/plain"});
        res.end('Hello World!');
})

app.listen(8000);

```

Curl call - `curl -H "Accept-Encoding: gzip" -vvv http://`hostname`:8000/`

----- I found there is slight error in `res.end`, where it doesnt check for `threshold`, if there is `_header`, which 
is causing this error. (my guess)

If I do sthing like this in `res.end`, it fixes the error
```
      if (!this._header) {
        len = Number(this.getHeader('Content-Length')) || len
        checkthreshold(len)
        this._implicitHeader()
      } else {
       //Check threshold irrespective
       checkthreshold(len)
      }
      if (!stream || !compress) { //adding the no compress too
        return end.call(res, chunk, encoding)
      }
```
But I am not sure if it has consequences, in `res.write`, there is a check for `threshold` only if there is a `Content-Length` header.

So I guess the fix might be little complicated than this.

**Comment by dougwilson** [comment]
Your fix is impossible--once `res._header` has been set, the headers have already been written out to the client, at which point we cannot alter headers, like adding `Content-Encoding` to the response. If you still think it works, though, would you be willing to make a PR?

**Comment by dougwilson** [comment]
Basically, the logic is this:

  * If `res.end` is called and we have not written the header to the network yet, we can either judge `Content-Length`, or whatever was written (since it's `res.end` without a header yet, it means it's the entire body).
  * If `res.write` is called and we have not written the header to the network yet, we can judge `Content-Length`, since it's the body size, but nothing else, since we don't know how big the body is going to be otherwise without buffering into memory (and going OOM quite easily).

You cannot make any compression decisions once the header has been written to the client, because we cannot possibly add or remove a header any longer.

**Comment by vsacheti** [comment]
This issue was more to highlight an issue rather than providing fix. 

The issue is, its compressed even when the content is less than the threshold.

As I mentioned in my original comments itself too, that that fix will be definitely more complicated than this, it was just to highlight that checkthreshold is not happening if the _header is set, which I can see from your comments, why.


I understand what you are saying.

**Comment by dougwilson** [comment]
Gotcha. We won't be changing anything in this module, but I will update the documentation on the `threshold` option to explain that it's only guaranteed to work if you provide a `Content-Length` header. If you don't, then we make our best guess and simply default to compression if we cannot determine what the length is going to be.

**Comment by dougwilson** [comment]
And of course, the reason it's unsolvable is because `res.writeHead` is a sync API, so we cannot delay the write to wait for the call to `res.end`, etc.

**Comment by dougwilson** [comment]
I have added this information to the documentation: https://github.com/expressjs/compression#threshold

**Comment by vsacheti** [comment]
Yeah I think the docs adds more clarity.

I was thinking about if there is any way to resolve this issue and its hard to resolve, coz the headers are already sent(as you mentioned), unless writeHead is monkey-patched, which looks like too much engineering. :).

Thanks for updating the docs.
