### ISSUE TITLE
Question - does this lib do compression on a separate thread?

### ISSUE THREAD

**Issue by ORESoftware** [expressjs/compression#48]
Just wondering for my own knowledge if ZLIB does the compression on a separate thread than the main JS thread in Node, or does it matter?

**Comment by ORESoftware** [comment]
well technically it wouldn't be a separate thread, it would be a separate Node.js process I guess, and this seems unlikely. So how does compression not slow down your server then?

**Comment by dougwilson** [comment]
This library simply uses Node.js's `zlib` library. Node.js uses a thread pool for compression, encryption, file I/O and DNS lookups. You can find out more details by asking the Node.js core team for how the asynx zlib functionality works, if you wish, as they would be able to explain it much better than myself.

But to sub it up: the operations run in a thread pool in the Node.js process.

**Comment by dougwilson** [comment]
Here is a link to a thread with the answer on the Node.js mailing list, answered by a core committer: https://groups.google.com/forum/#!topic/nodejs/WR4coxriQSM

**Comment by ORESoftware** [comment]
thanks that's great info

**Comment by dougwilson** [comment]
No problem!

**Comment by ORESoftware** [comment]
hey Doug, here is my question of the hour - the way this is set up it will compress files for every request. so if a client A requests a text based asset, Express will compress it and then serve it.  Is there a way to GZIP assets with ZLIB before the server starts?

**Comment by ORESoftware** [comment]
in other words, is there a way to either 

(1) cache the results of gzip process (saving .gz files onto server) during server runtime
(2) write out .gz file(s) onto the server before it starts up

it seems like (2) is a much better idea, especially since I personally really only have one production file to deploy, I can just gzip the one file before the server starts and then point to a .gz file instead of a .js file in my index .html file.

**Comment by ORESoftware** [comment]
I just saw the question about caching from another user, so I opened up a new issue/question. Hopefully it's a good one, probably better to answer the question over there than here. I can move/delete the comments from the last hour on this thread into the new issue.

**Comment by dougwilson** [comment]
Hi! There certainly is, though not with this module (which is simply on-the-fly compression, meant for dynamic content rather than static content). There are other modules on npm just for the specific purpose of doing this with static files (typically your pre-compress with a grunt/gulp task and then serve with a specialized module).

**Comment by ORESoftware** [comment]
ok thanks! I guess I can add the names to those modules to this thread later, it all makes sense and I appreciate the info
