### ISSUE TITLE
GZIP components before Express server starts

### ISSUE THREAD

**Issue by ORESoftware** [expressjs/compression#49]
Originally this question was on a pre-existing issue thread, but thought I would open up a new question to keep it separated.

There was a question about caching the results of compression, but I think maybe it's better to GZIP assets before the server starts - seems less messy and even more efficient.

So, if this is possible, it would probably require streaming the results of the compression to the filesystem using the command line or a build system like Gulp or Grunt.

In my case, I am only working with one deployment file, so this would be very straightforward. So I am looking for a way to configure this module so that it can be used with a build system like grunt or gulp, or if someone has a better idea...this is more of a discussion I guess.

**Comment by dougwilson** [comment]
There are ways to do this, but this module is specifically only for compression of dynamic content (or I guess compressing static content over and over again--but production is better served by off-loading static file serving from Node.js).

I don't know the names of these modules, as I simply put static content on Akamai, but if you can find them and tell me, I can always list them in the README here for future users.

**Comment by ORESoftware** [comment]
Ok cool, yeah I can send you over some info that I discover on this. You should compress your static assets before putting them on Akamai :)

**Comment by dougwilson** [comment]
> You should compress your static assets before putting them on Akamai :)

I do.

**Comment by ORESoftware** [comment]
cool - do you use a Node.js module for that compression? recommendation?

**Comment by dougwilson** [comment]
Just the `gzip` command line program from bash, unfortunately, which is why I don't know the name of any grunt/gulp plugins off-hand :(

**Comment by ORESoftware** [comment]
np, that helps thx

**Comment by ORESoftware** [comment]
readme:

http://www.quora.com/If-you-use-the-highest-compression-rating-with-gzip-does-it-take-longer-to-gunzip

**Comment by ORESoftware** [comment]
I was looking through the code for this module/lib, and I don't see any code in index.js that has to do with running the compression on a separate thread - where can I find that code? thx

**Comment by dougwilson** [comment]
It is part of Node.js C++ source code for the zlib module; you won't find it here. If you are interested in seeing that, you will need to ask over on the Node.js repo.

**Comment by ORESoftware** [comment]
ok thanks doug!
