### ISSUE TITLE
Compress .data files

### ISSUE THREAD

**Issue by cruzlutor** [expressjs/compression#54]
Hi, i want to compress .data files for unity webgl
It is possible?

**Comment by dougwilson** [comment]
Hm, I'm not sure. Can you provide some more information? I'm just not quite sure what that is.

In general, this module is a dynamic compression module that transparently compresses your responses from your Express server. The standard way to use it is here: https://github.com/expressjs/compression#expressconnect

**Comment by cruzlutor** [comment]
Maybe not work by default, the .data file is a application/octet-stream mime type

**Comment by dougwilson** [comment]
Ah, yes. The type `application/octet-stream` signifies binary data and typically standard compression algorithms do not compress data well that is non-repeating (and typically binary data fits in this bucket). It's definitely possible that the binary data used in your specific .data files can be compressed, though.

All you need to do to start compressing your .data files with this module is extend the `filter` option (example in https://github.com/expressjs/compression#filter-1).

Depending on how you are serving these files, you can change the definition to best fit that. I'm going to provide an example here which will always compress anything you serve from the `/webgl/` path on your server, even if they are binary files:
```
var compression = require('compression')
var parseUrl = require('parseurl')

// set up your app

app.use(compression({filter: shouldCompress}))

function shouldCompress(req, res) {
  // customize this if logic to meet your needs
  if (parseUrl(req).pathname.substr(0, 7) === '/webgl/') {
    // always compress responses to the /webgl/ directory
    return false
  }

  // fallback to standard filter function
  return compression.filter(req, res)
}
```
