### ISSUE TITLE
Compression runs but response is not encoded

### ISSUE THREAD

**Issue by savarex** [expressjs/compression#55]
Hi, 
I created a very basic example on my machine (Windows 10, NodeJs 4.2.1, Express 4.13.3) but I can't make compression module to run properly.

I'm making a simple request with Accept-Encoding : gzip.
Using DEBUG=compression I can see that compression module make compression (or at least logs it) 

```
Example app listening at http://:::3000
  compression gzip compression +0ms
```
**But content is not compressed!**
This is the RAW output of my request. It misses "Content-Encoding : gzip" header and content is not gzipped.
```
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/plain
ETag: "472456355"
Vary: Accept-Encoding
Date: Sun, 18 Oct 2015 13:27:45 GMT
Connection: keep-alive
Transfer-Encoding: chunked

c
Hello World!
0
```

Below there is the code I used.
```javascript
var compression = require('compression')
var express     = require('express')

var app = express()

app.use(compression({
	threshold : 0
}))

app.get('/', function (req, res) {	
	res.setHeader('Content-Type', 'text/plain')
        res.send('Hello World!');
});

var server = app.listen(3000, function () {
    
    var host = server.address().address;
    var port = server.address().port;
    
    console.log('Example app listening at http://%s:%s', host, port)
});
```

I tried also removing node_modules and running
````
npm cache clean
npm install
```

Any suggestions? I can't believe I am the only one with this type of issue!

Many thanks,
Emanuele

**Comment by savarex** [comment]
Sorry, I was in wrong.
On Windows neither Chrome and Fiddler let me really know what is going behind the scenes.
I downloaded curl for windows (from here http://curl.haxx.se/download.html) to understand that all was working fine.

Finally, command below allows me to see the gzipped content  :)
```
curl "http://localhost:3000/" -H "Accept-Encoding: gzip, deflate, sdhc" --raw
```

**Comment by ali-khabbaz** [comment]
i had the same problem, thank god , after 6 hours in testing, finally !
