### ISSUE TITLE
defaults for ARM

### ISSUE THREAD

**Issue by usernameisalreadytaken2014** [expressjs/compression#60]
The default gzip compression level is 6.  A bit high compared to eg. hardware load balancers that usually default to 1.

Not a big problem on for example a modern Intel/AMD CPU.  But causes a *major* slowdown when the compression module is installed on a site that runs on fx. a Raspberry Pi.

So here's a feature request.
```
if (process.config.variables.host_arch == 'arm') level = 1;
```
In other words, if NodeJS was compiled and is running on ARM (either v6l or v7), then set a default compression level of 1, to avoid extremely sluggish sites after installing the compression module.

**Comment by usernameisalreadytaken2014** [comment]
(for reference, default settings for a hardware load balancer:
 https://support.f5.com/kb/en-us/solutions/public/3000/300/sol3393.html
 see "gzip compression level".)

**Comment by usernameisalreadytaken2014** [comment]
As a side note, the F5 guys know what they are doing.  So we can assume that they have a very good reason for setting the level to 1.  Likely decided on after lots of testing.

If you would like, I can do a bit of research and check other web server software and appliances for http traffic delivery and see what other people choose as defaults.  I have a feeling that the industry standard is not 6. :-)

**Comment by usernameisalreadytaken2014** [comment]
Some relevant graphs:
https://mscblogs.blob.core.windows.net/media/owscott/Media/IIS7CompressionRatio.jpg
https://mscblogs.blob.core.windows.net/media/owscott/Media/IIS7Compression-TTFB.jpg

**Comment by dougwilson** [comment]
Hi! You'll notice in our source code, we do not actually set any defaults anywhere, so there is no where we can just change the default to level 1 for ARM. All defaults are handled in Node.js core, we just document them on our README because people kept complaining that they had to go read Node.js core documentation :)

This means you have two options here:
1. Get Node.js core to provide a different default.
2. Publish a module to npm that wraps this module with a different default, using the public API options we provide.

I hope that makes sense :)

**Comment by usernameisalreadytaken2014** [comment]
@dougwilson

Could you point to where in NodeJS the default is implemented?

**Comment by dougwilson** [comment]
Hi @usernameisalreadytaken2014, I'm not certain. I guess it is https://github.com/nodejs/node/blob/v5.7.0/lib/zlib.js#L27

**Comment by usernameisalreadytaken2014** [comment]
More like https://github.com/nodejs/node/blob/v5.7.0/lib/zlib.js#L31 yeah?

I think the zlib module is intended for general usage.

The compression module is a special case that does live compression during streaming.

Other users of the zlib module may expect the compression level to be a constant, in particular modules that use zlib to compress files on disk or other non-streaming purposes.

In short, after thinking about it a bit, it seems to me that the correct place to adjust the level to something suitable for streaming is inside the compression module (even if it is initially defined to some default value in zlib).

**Comment by dougwilson** [comment]
> the correct place to adjust the level to something suitable for streaming is inside the compression module (even if it is initially defined to some default value in zlib).

You need to do this yourself, or publish a module to npm wrapping this module to do the same thing:

```js
app.use(compression({
  level: process.config.variables.host_arch == 'arm' ? 1 : -1
}))
```

**Comment by usernameisalreadytaken2014** [comment]
OK, thank you.

(Might be useful to include this as a hint in the documentation, in case there are other people out there using NodeJS + compression on a Raspberry Pi platform.  OTOH, I guess github issues is a kind of documentation too ;-).)
