### ISSUE TITLE
Chrome not caching js and css with compression enabled

### ISSUE THREAD

**Issue by aanuprab** [expressjs/compression#64]
I turned on compression. It works fine as expected. But chrome for some reason does not like something with this compression in that it does not cache js and css files. while images and fonts are cached.

I found developers having similar issues here http://stackoverflow.com/questions/33421141/sails-not-caching-compressed-files

**Comment by dougwilson** [comment]
Hi! Thanks for the report. I cannot reproduce on Chrome myself. Can you provide what the suggested change we need to make to fix the issue?

**Comment by aanuprab** [comment]
@dougwilson I don't know what's causing this. But it took me a day to nail this down to compression. Can you provide me the base express.js code that works for you. I can try to see if could reproduce.

**Comment by dougwilson** [comment]
The example https://github.com/expressjs/compression#expressconnect with `express.static` at the bottom,

**Comment by dougwilson** [comment]
Here is my application setup:
```
$ npm i express compression
compression@1.6.0 node_modules\compression
+-- bytes@2.1.0
+-- vary@1.1.0
+-- on-headers@1.0.1
+-- compressible@2.0.6 (mime-db@1.20.0)
+-- debug@2.2.0 (ms@0.7.1)
+-- accepts@1.3.0 (negotiator@0.6.0, mime-types@2.1.7)

express@4.13.3 node_modules\express
+-- escape-html@1.0.2
+-- methods@1.1.1
+-- utils-merge@1.0.0
+-- merge-descriptors@1.0.0
+-- cookie-signature@1.0.6
+-- array-flatten@1.1.1
+-- cookie@0.1.3
+-- path-to-regexp@0.1.7
+-- vary@1.0.1
+-- range-parser@1.0.3
+-- content-type@1.0.1
+-- fresh@0.3.0
+-- etag@1.7.0
+-- parseurl@1.3.0
+-- content-disposition@0.5.0
+-- serve-static@1.10.0
+-- depd@1.0.1
+-- qs@4.0.0
+-- finalhandler@0.4.0 (unpipe@1.0.0)
+-- on-finished@2.3.0 (ee-first@1.1.1)
+-- debug@2.2.0 (ms@0.7.1)
+-- proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
+-- send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
+-- type-is@1.6.9 (media-typer@0.3.0, mime-types@2.1.7)
+-- accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.7)

$ node -v
v0.10.33

$ cat app.js
var compression = require('compression')
var express = require('express')

var app = express()

// compress all requests
app.use(compression())

app.use(express.static(__dirname + '/public'))

app.listen(3000)

$ cat public/main.css
html, body { font-face: arial }
```

Once I open http://localhost:3000/main.css once in Chrome, navigating there again shows that it gets a 304 response:
![304](https://cloud.githubusercontent.com/assets/67512/11259351/fdb7191a-8e2e-11e5-965b-b2cd9224f89f.png)

In addition, when I click on copy as cURL for that request Chrome made and run it, here is the result, which also shows it was a 304:
```
$ curl 'http://localhost:3000/main.css' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'If-None-Match: W/"21-1511d3cb6e8"' -H 'Connection: keep-alive' -H 'If-Modified-Since: Thu, 19 Nov 2015 00:54:57 GMT' --compressed -v
* Adding handle: conn: 0x4c3780
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x4c3780) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 3000 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /main.css HTTP/1.1
> Host: localhost:3000
> Accept-Encoding: gzip, deflate, sdch
> Accept-Language: en-US,en;q=0.8
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
> Cache-Control: max-age=0
> If-None-Match: W/"21-1511d3cb6e8"
> Connection: keep-alive
> If-Modified-Since: Thu, 19 Nov 2015 00:54:57 GMT
>
< HTTP/1.1 304 Not Modified
< X-Powered-By: Express
< Accept-Ranges: bytes
< Cache-Control: public, max-age=0
< Last-Modified: Thu, 19 Nov 2015 00:54:57 GMT
< ETag: W/"21-1511d3cb6e8"
< Date: Thu, 19 Nov 2015 00:59:05 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
```

**Comment by aanuprab** [comment]
@dougwilson  - OK, I narrowed it down little further, if the connection is SSL, this compression routine seems to have some problem.

Can you add these to your setup and try it out? Just create a keys folder and drop a self signed certificate. If you need mine let me know.


app.use(compression());
app.use(express.static(path.join(__dirname, 'public') ,{ maxAge: 31536000000, etag:false }));
var options = {
  key: fs.readFileSync('./keys/privatekey.pem'),
  cert: fs.readFileSync('./keys/cert.pem'),
  passphrase: 'localhost'
};

https_Secure_Server = https.createServer(options, app).listen('443', function(){
  console.log('server listening on port: 443');
});

**Comment by dougwilson** [comment]
Are you sure the SSL is the problem and not the fact that you disabled ETags, which play a critical role in caching? Does it work if you enable ETags?

**Comment by dougwilson** [comment]
You can read the Google Chrome documentation at https://developers.google.com/speed/docs/insights/LeverageBrowserCaching?hl=en which seems to indicate you need ETags for caching:

> When the server returns a response it must provide the Cache-Control and ETag headers

**Comment by aanuprab** [comment]
etag is not the problem. I even removed etag and re-tested SSL vs non-SSL requests.

SSL - fails
Non-SSL - pass.

**Comment by dougwilson** [comment]
Unfortunately I have no idea. I don't really use Chrome and don't know what the caching rules are. If you can tell me what I need to change in this module to fix the issue, that's likely the only way to move this forward. I assume you have tested over SSL with non-self-signed certificates? I found https://code.google.com/p/chromium/issues/detail?id=110649 which seems to indicate Chrome will never cache things from sites with self-signed certificates.
