### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by arboreal84** [expressjs/compression#75]
I was looking at a memory leak and found:
![image](https://cloud.githubusercontent.com/assets/5076519/13546771/97f685b0-e26c-11e5-93a6-05c9907435c1.png)

Looking at this, it seems that this closure might be leaking.
```javascript
      // compression
      stream.on('data', function(chunk){
        if (write.call(res, chunk) === false) {
          stream.pause()
        }
      });
```

**Comment by partycoder** [comment]
In the context of the closure, `stream` is `this`.

**Comment by tunniclm** [comment]
This looks like a cycle through the same 3 objects.

**Comment by arboreal84** [comment]
note that `stream` within the context of that closure is `this`.

**Comment by dougwilson** [comment]
Hi @arboreal84, using tools like `node-inspector`, I have not been able to find any memory leak, at least in Node.js 0.10. Can you explain more on specifically why you think there is a memory leak and what methodology you used to determine this?

I even tried changing `stream.pause()` to `this.pause()` as it seems you are suggesting and it made no difference in the heap snapshots I'm taking.

If you can, please (1) provide a pull request fixing the memory leak, along with detailed information for how you identified the source and why specifically the change fixes the leak or (2) provide me with detailed instructions on exactly how to reproduce the memory leak so I can debug it.

**Comment by arboreal84** [comment]
I some `IncomingMessage` objects in my heap snapshots being retained in this way for long periods of time. If you have verified there's no memory leak feel free to close this issue.

**Comment by dougwilson** [comment]
Hi @arboreal84, I wouldn't say I've verified no memory leak, just that I couldn't figure it out based on the tools I was using, and without code to reproduce it from you, I'm just using this module with nothing else, like in the tests. It's certainly possible you are experiencing some kind of memory leak, perhaps on a specific version of Node.js, or in combination with some other module(s). There just isn't enough information provided here for me to reproduce, and trying to reproduce with this module alone didn't seem to yield any results.

**Comment by arboreal84** [comment]
I tested on node v0.10.36 and v0.10.42.

**Comment by dougwilson** [comment]
Gotcha. I was using Node.js 0.10.38. I can't image those versions would be very different. Perhaps there is more going on in the code you are using? Can you provide complete code that reproduces the leak I can test against?

**Comment by dougwilson** [comment]
Also, please note the versions (even this module) of any modules your code uses so I can install the same versions.

**Comment by arboreal84** [comment]
I am just using:
```javascript
app.use(compression())
```
Package version is 1.4.4

**Comment by dougwilson** [comment]
Thanks for that @arboreal84, but I assume that is not the only line in your application? I have found many times a memory leak can occurs from different modules interacting in a certain way. I tested the case were `compression` was the only thing that existed, as I have no idea all the other modules, middlewares, etc. that you may be using.

You may also want to consider upgrading this module to at least the most recently published version and testing your issue before reporting, as it is many versions out of date and you may even be experiencing a fixed issue.
