### ISSUE TITLE
Content-encoding header

### ISSUE THREAD

**Issue by danb-cws** [expressjs/compression#79]
I have compression set up and can see the gzipped response being correctly returned using curl, but I dont see a "content-encoding: gzip" header being returned.
Is there some reason for this behaviour? I've not seen any issues with my test browsers, the only problem is the audit in chrome reports "enable gzip compression" when it IS already enabled...

**Comment by dougwilson** [comment]
Hi! Unfortunately there is not enough information here for me to help you, besides saying we have extensive unit tests and you'll need to provide a pull request if you believe you are encountering an issue.

If you would like me to take a look, please provide all the following:

1. Version of Node.js
2. Version of this module 
3. Complete code that reproduces the issue. It needs to be a single file and I will copy paste it and run it. Please do not use any other modules besides this one and Node.js core modules, unless you are trying to demonstrate this module not working with another.
4. Complete steps to run that script, how to reproduce the issue, and how to know I am reproducing it.

**Comment by danb-cws** [comment]
Node 5.7.1, express 4.9, compression 1.6.1

Server code:

var express = require('express')
var compression = require('compression')
var app = express()
app.use(compression({threshold: 0}))
app.listen(3000)

app.get('/hello', (req, res) => {
  var result = '';
  result = '<h1>hello world</h1>';
  res.send(result);
});

Then in curl:
curl "http://localhost:3000/hello" -H "Accept-Encoding: gzip, deflate, sdhc" --raw

Result: compressed content served, but no content-encoding: gzip header is sent

**Comment by dougwilson** [comment]
Your cURL command is not set to show any headers. You need to at least add `-i` according to the cURL manual. Here are the steps I followed based on your instructions and the only issue I saw was your cURL issue highlighted above:
```
$ cat app.js
var express = require('express')
var compression = require('compression')
var app = express()
app.use(compression({threshold: 0}))
app.listen(3000)

app.get('/hello', (req, res) => {
  var result = '';
  result = 'hello world';
  res.send(result);
});

$ npm i express@4.9 compression@1.6.1
compression@1.6.1 node_modules\compression
├── on-headers@1.0.1
├── bytes@2.2.0
├── vary@1.1.0
├── compressible@2.0.7 (mime-db@1.22.0)
├── accepts@1.3.2 (negotiator@0.6.0, mime-types@2.1.10)
└── debug@2.2.0 (ms@0.7.1)

express@4.9.8 node_modules\express
├── merge-descriptors@0.0.2
├── utils-merge@1.0.0
├── fresh@0.2.4
├── escape-html@1.0.1
├── range-parser@1.0.3
├── cookie-signature@1.0.5
├── vary@1.0.1
├── cookie@0.1.2
├── parseurl@1.3.1
├── media-typer@0.3.0
├── methods@1.1.0
├── finalhandler@0.2.0
├── serve-static@1.6.5
├── path-to-regexp@0.1.3
├── depd@0.4.5
├── qs@2.2.4
├── type-is@1.5.7 (mime-types@2.0.14)
├── on-finished@2.1.1 (ee-first@1.1.0)
├── etag@1.4.0 (crc@3.0.0)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── debug@2.0.0 (ms@0.6.2)
├── send@0.9.3 (destroy@1.0.3, ms@0.6.2, mime@1.2.11, on-finished@2.1.0)
└── accepts@1.1.4 (negotiator@0.4.9, mime-types@2.0.14)

$ node -v
v5.7.1

$ node app &
[1] 21556

$ curl -i "http://localhost:3000/hello" -H "Accept-Encoding: gzip, deflate, sdhc" --raw
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
ETag: W/"b-d4a1185"
Vary: Accept-Encoding
Content-Encoding: gzip
Date: Mon, 04 Apr 2016 12:53:55 GMT
Connection: keep-alive
Transfer-Encoding: chunked

a
▼      ♂
15
♂   ╔W(╧/╩I☺ à◄J
0
```

**Comment by danb-cws** [comment]
Strange that I dont see it in chrome with the exact same request:

![image](https://cloud.githubusercontent.com/assets/2528249/14249083/e3a43df2-fa6f-11e5-823f-7289b88bf4e7.png)

**Comment by dougwilson** [comment]
No idea. Here is the Chrome screenshot for the app you gave me on my Chrome:
![capture](https://cloud.githubusercontent.com/assets/67512/14250060/c3b84972-fa4a-11e5-8d97-fac81ab4f770.PNG)

**Comment by lethaldose** [comment]
set `{threshold:0}` in options

**Comment by danieden** [comment]
Hello

I is having same error. This is my code.

var acceptEncoding = req.headers['accept-encoding'];
        if (!acceptEncoding) { acceptEncoding = ''; }
        if (acceptEncoding.match(/\bdeflate\b/)) {
            zlib.gzip(JSON.stringify(Response), function (err, result) {
                if (!err) {
                    //res.writeHead(200, { 'content-encoding': 'gzip' });
                    res.header('Content-Length', result.byteLength);
                    res.setHeader('transfer-encoding', '');
                    res.setHeader('content-encoding', 'deflate');
                    res.send(result, 200);
                }
            });
        }
        if (acceptEncoding.match(/\bgzip\b/)) {
            zlib.gzip(JSON.stringify(Response), function (err, result) {
                if (!err) {
                    //res.writeHead(200, { 'content-encoding': 'gzip' });
                    res.header('Content-Length', result.byteLength);
                    res.setHeader('transfer-encoding', '');
                    res.setHeader('content-encoding', 'gzip');
                    res.send(result, 200);
                }
            });
        }
        else {
            res.send(JSON.stringify(Response), 200);

When I check the variable result see process working but node js express changes headers to "transfer-encoding chunked"

Do anybody knows why doing that??

![error](https://user-images.githubusercontent.com/3663743/37578683-d2b429fc-2b10-11e8-8718-21281d34dc15.png)

**Comment by eshwarenm** [comment]
Had the same issue. I used 
`app.use(compression({threshold: -1}));`
and it works now.
