### ISSUE TITLE
Not compressing images

### ISSUE THREAD

**Issue by rafaelms87** [expressjs/compression#82]
Is there any configuration necessary to enable image compression?

**Comment by dougwilson** [comment]
Hi @rafaelms87, by default, only compressible types are compressed. Most image formats are already compressed, and running them through gzip does not produce a meaningful CPU time vs transfer size tradeoff, spending a lot of CPU time with a very small reduction in transfer size.

If you would like to compress them, just use the `filter` option (https://github.com/expressjs/compression#filter) to not filter images.

Using the example in the readme and adjusting to just allow all images, it would look like the following:
```js
app.use(compression({filter: function shouldCompress (req, res) {
  if (/^image\//.test(res.getHeader('Content-Type'))) {
    // compress any image format
    return true
  }

  // fallback to standard filter function
  return compression.filter(req, res)
}}))
```

I hope this helps!
