### ISSUE TITLE
Force compression to client don't work

### ISSUE THREAD

**Issue by zhaoyou** [expressjs/compression#83]
I want compression response body to client always , Whether the client have any Settings。My Client App is poor what can't set any request header, but can handle compression data.

``` js
app.get('/device', auth_identity, compression({filter: function(req, res) { return true;}}),device);
```

```
node: v4.2.2
compression: 1.6.1
express : 3.4.4
```

Why ? thanks.

**Comment by zhaoyou** [comment]
@dougwilson

**Comment by dougwilson** [comment]
Hi @zhaoyou, sorry I haven't gotten back to you yet. Yes, this is a hole in the module currently, that you cannot override the way the module checks if the client is capable of receiving compressed content, and I think it would be good to add it.

In the meantime, I would like the offer the following work-around for your use-case:
```js
app.get('/device', auth_identity, always_compress, compression(), device)

function always_compress (req, res, next) {
  req.headers['accept-encoding'] = 'gzip'
  next()
}
```

**Comment by zhaoyou** [comment]
@dougwilson  Thanks 👍  for your explanation and suggestion.

**Comment by bjohansebas** [comment]
Allowing the option to choose a default encoder can solve this issue.
