### ISSUE TITLE
Always setting vary causes issues with Akamai

### ISSUE THREAD

**Issue by frkris** [expressjs/compression#85]
https://github.com/expressjs/compression/blob/master/index.js#L153

We always set "Vary: Accept-Encoding", even in the cases where we don't compress because response is too small.

This causes issues with Akamai CDN, because

`The Vary header instructs Akamai Servers that content may differ based on some characteristic and hence, it is uncacheable. This is valid behavior per RFC HTTP/1.1. Specifically, Akamai will not cache content if the Origin Server response includes a Vary header with a value other than Vary: Accept-Encoding. ​_Akamai will cache responses with ​*Vary: Accept-Encoding*​ only if they are accompanied by ​*Content-Encoding: gzip*​._​`

I.e., Akamai always forwards these requests to origin which is a potential disaster of a heavy traffic website.

**Comment by dougwilson** [comment]
Ok, then it sounds like you should simply set `threshold: 0` in your options? Because this is a dynamic module, just because we don't compress a small response doesn't mean the response for the same resource may not be larger at a later time, thus we *MUST* send the `Vary` header.

**Comment by frkris** [comment]
@dougwilson Ah, very good point indeed. Thank you.
