### ISSUE TITLE
Pre Gzipped content

### ISSUE THREAD

**Issue by sandysaders** [expressjs/compression#87]
if file is already gzipped prior to hitting middleware will it gzip again?
I have my javascript bundled and gzipped with webpack. However all other assets and non js code is not gzipped and need this module for them. If it hits my js that is gzipped will it gzip again or cause problems on the client?

**Comment by domadams** [comment]
@sandysaders - I have a piece of middleware that may help you here. https://www.npmjs.com/package/pre-compressed-assets

This will send the .gz file to the browser before you hit the compression middleware. I had to create it to avoid the problem you describe. 👍

**Comment by dougwilson** [comment]
Hi @sandysaders, without knowing how you are sending these files, it's really hard to answer the question, but I can provide the following information that should help:

* This module will not compress any response that already includes a `Content-Encoding` header. This means that if you are trying to serve up pre-compressed content to a client, you are most likely setting this header on that response, such that the client will be able to decompress it. In this case, this module will not compress it again.
* This module will not compress any response where the `Content-Type` does not look compressible. This means if you are trying to serve up a literal `.gz` file, then it will not compress it again. You can even adjust this and even ignore whatever you need using the `filter` option: https://github.com/expressjs/compression#filter
