### ISSUE TITLE
How to know if files are being successfully compressed?

### ISSUE THREAD

**Issue by sandysaders** [expressjs/compression#88]
Hello,

I'm wondering to see how I can know if files are being compressed? So far I have the following:

```js
var express = require('express')
var compression = require('compression')
var zlib = require('zlib');

var app = express()
app.use(compression({level: 9}))
...
```

When I make a request at localhost how do I confirm in the browser that the files that we're sent over are in fact gzipped and uncompressed via the browser?

I get the following: 
![screen shot 2016-07-21 at 2 20 42 pm](https://cloud.githubusercontent.com/assets/19610736/17033961/97bdcda2-4f4e-11e6-963a-f775ef17cfe5.png)
![screen shot 2016-07-21 at 2 22 02 pm](https://cloud.githubusercontent.com/assets/19610736/17033968/a1e22de6-4f4e-11e6-9281-1ef356866fef.png)

![screen shot 2016-07-21 at 2 21 02 pm](https://cloud.githubusercontent.com/assets/19610736/17033958/9026bca2-4f4e-11e6-9d42-0625553d1a20.png)

**Comment by hadijaveed** [comment]
+1 I have the same question

**Comment by blakeembrey** [comment]
It doesn't look like it's compressed. Usually a compressed response will contain `Content-Encoding: gzip` as the response.

**Comment by hadijaveed** [comment]
yes but with same code posted by @sandysaders it gives the same `Accept-Encoding: gzip, deflate, sbch`. Can you suggest how can I make it work ?

**Comment by blakeembrey** [comment]
Can you share some code so I can reproduce it? The original issue was a general question as far as I know.

**Comment by hadijaveed** [comment]
I am sorry there was a typo in my code. So it is working now !

**Comment by blakeembrey** [comment]
Awesome, great to hear. I'll close this as the question was answered, but if there's any other issues feel free to continue the discussion.

**Comment by hilleer** [comment]
It might help others if you post the solution. I found this issue having a similar problem, but couldn't see what was wrong, as you didn't post the solution 👎

**Comment by blakeembrey** [comment]
@hilleer It might have if you have an issue to post the issue you're having too. This issue was a question, and the question was answered https://github.com/expressjs/compression/issues/88#issuecomment-235494836.

**Comment by hilleer** [comment]
Fair enough :-) It was more like a solution - to post the solution he found.
