### ISSUE TITLE
Testing with supertest always activates compression even with no request header

### ISSUE THREAD

**Issue by ugolas** [expressjs/compression#89]
Hi,

I've added the middleware without any special configurations, and am trying to test is using supertest.js.

In one test case I'm sending a POST request without specifying the 'Accept-Encoding' header, and still get in response the 'content-encoding' & 'transfer-encoding' headers.

Testing this in ARC/POSTMAN works as expected.

Any ideas?

**Comment by blakeembrey** [comment]
Superagent is probably adding the accept encoding header for you.

**Comment by blakeembrey** [comment]
Confirmed. I can see the header is set in superagent.
