### ISSUE TITLE
compression gzip not working (expressjs - compression library)

### ISSUE THREAD

**Issue by alirezavalizade** [expressjs/compression#95]
I use from compression library and still not working.. this is my config :

```js
const app = express();

app.use(compression());

app.use("/public", express.static(path.join(path.resolve(__dirname, '../../public'))));
```

![noat4](https://cloud.githubusercontent.com/assets/14992757/19827487/d7ac2824-9db8-11e6-82c4-97696a2a658c.png)

**Comment by dougwilson** [comment]
By default, this module does not compress responses that contain already compressed assets, like JPEG images. You can use the filter option to override this behavior if you like.

**Comment by alirezavalizade** [comment]
@dougwilson can you show me How?

**Comment by dougwilson** [comment]
Unfortunately I am on a phone, and it's impractical to type code here. You can see the documentation for filter at https://github.com/expressjs/compression/blob/master/README.md#filter and there is a filter override example in the readme as well. If you want to simply compress all types, just return false in the function.

**Comment by dougwilson** [comment]
> just return false in the function.

I meant to type return true.

**Comment by alirezavalizade** [comment]
```
var compression = require('compression')
var express = require('express')

var app = express()

// compress all responses
app.use(compression())

// add all routes ===> what about this comment?I think it meaning use compress all routes and static files
```

**Comment by dougwilson** [comment]
Hi @alirezavalizade I'm not sure I understand.

**Comment by dougwilson** [comment]
```js
app.use(compression({
  filter: function () { return true; }
}));
```

**Comment by yairtawil** [comment]
Thanks. it's works for me
Saved my day.
