### ISSUE TITLE
Simple example not working...

### ISSUE THREAD

**Issue by Altneu** [expressjs/compression#96]
What am I missing here?

```js
var comp = require('compression');
var express = require('express');
var fs = require('fs');
var app = express();

app.use(comp());

app.get('/test', function(req,res,next) {
  fs.readFile('public/sample.json', function(err, data) {
    res.set({'Content-Type': 'application/json'});
    res.send(data.toString());
  });
});

app.listen(8080);
```
```
  "dependencies": {
    "compression" : "1.6.2",
    "express": "4.14.0"
  }
```

and node 4.4.1. 

The response is not showing as compressed in chrome or firefox.  I used debug to trace and added my own debug entries and have verified that the compression module is running, compressible is returning true.  Any ideas why this wouldn't work?

**Comment by Altneu** [comment]
I have already deleted node_modules and cleared npm cache.  Still not working.

**Comment by dougwilson** [comment]
Hi @Altneu , by default the threshold for compression is 1KB (see https://github.com/expressjs/compression#threshold). Is your remove 1KB or larger?

**Comment by Altneu** [comment]
Yes it is.

**Comment by Altneu** [comment]
![image](https://cloud.githubusercontent.com/assets/4061286/19868761/e4113532-9f7f-11e6-95a1-9fd7ad9b66b6.png)

**Comment by dougwilson** [comment]
Hi @Altneu can you use something else besides Chrome? As far as I'm' aware, Chrome will _never_ show the `Content-Encoding` header in their inspector, as that is a long standing bug, so it's not possible to tell if it's being compressed in Chrome. I'm told that if you instead use the network tab and see if the "Size" is different from the "Content" then it's compressed.

**Comment by dougwilson** [comment]
Another option is if you set your environment variable `DEBUG=compression` and paste the logs for your request here, it will tell what is happening to your request.

**Comment by dougwilson** [comment]
Apparently this column method works too: https://www.youtube.com/watch?v=Q_k8JkQwe88

**Comment by Geex-Renzo** [comment]
Hi @Altneu and @dougwilson, I've been looking into it and honestly, I've made the exact same project as @Altneu and my response shows the gzip header and yes, in Chrome...
![image](https://cloud.githubusercontent.com/assets/16548072/19873402/1d655298-9fbf-11e6-926f-8004e137c900.png)
So honestly, I have no idea where it went wrong for @Altneu since I can't reproduce the problem.
I've used example json data from http://json.org/example.html, the "web-app" "servlet" "cofaxCDS" one, it's a little larger than 3KB.

**Comment by dougwilson** [comment]
Hi @Geex-Renzo I used @Altneu's example at the top with Node.js 4.4.1, even, but it was compressed. Obviously I had to guess the contents of the `public/sample.json` file, and of course it's weird that the app has a route for `GET /test`, yet the screenshot @Altneu added shows a request for `GET /test.json`, but IDK. It seems like there is a moving target here.

**Comment by Geex-Renzo** [comment]
Even though I made it in Node v6.8.1 this is a screenshot of my files
![image](https://cloud.githubusercontent.com/assets/16548072/19875016/c0c83446-9fc9-11e6-8a71-2a29d13b18d1.png)

**Comment by Altneu** [comment]
I modified just the route between screenshot and original code post. Its still not working for me.

**Comment by Altneu** [comment]
And I checked in multiple browsers. Debug shows compression code running properly.

**Comment by Altneu** [comment]
with debug enabled...

`  compression gzip compression +0ms
  compression gzip compression +7s
`

code ran
`var comp = require('compression');
var express = require('express');
var fs = require('fs');
var app = express();

app.use(comp());

app.get('/test.json', function(req,res,next) {
  fs.readFile('public/sample.json', function(err, data) {
    res.set({'Content-Type': 'application/json'});
    res.send(data.toString());
  });
});

app.listen(8080);`

chrome...
![image](https://cloud.githubusercontent.com/assets/4061286/19882412/efcbd710-9fe3-11e6-8d84-1b4f2a6070ca.png)

checked other browsers also, its not being compressed.

**Comment by Altneu** [comment]
Ok not sure if something changed in Chrome, but the issue was that both Chrome and Firefox were not showing the response as compressed even though it was. What was confusing was that both browsers did show responses as compressed if the request was secure.  I used to Fiddler to confirm that the compression was working properly.

**Comment by aminnairi** [comment]
I had a bug where compression was not working for me.

Here is my entrypoint.

```ts
server.use(express.static(join("..", "client", "build")));

server.use(cookieParser());

server.use(bodyParser.json());

server.use(compression({
  level: 9,
  threshold: 1
}));
```

The mistake was that the `compression` middleware was the last one. After checking the sources, it seems like it creates some kind of proxy for the stream methods of the response. And if I'm guessing right and that the order matters, no wonder why it does not work.

So after putting the `compression` middleware as the very first one before any other middleware, I started to see some compression working for my files (especially those static files in a React app).

```ts
server.use(compression({
  level: 9,
  threshold: 1
}));

server.use(express.static(join("..", "client", "build")));

server.use(cookieParser());

server.use(bodyParser.json());
```

Notice the order of the `compression` middleware in this case, now every static files gets served with compression.

I guess this should be documented somewhere in the `README.md` to let the users know that the order matters, even better with an example with some of the middlewares that the Express team is maintaining for instance.
