### ISSUE TITLE
compression does not work in express 4.14.0

### ISSUE THREAD

**Issue by KathyDinh** [expressjs/compression#97]
Hi,

I have tried for hours and couldn't manage to get gzip working in my local.

Here is my code:

```js
import express = require("express");
import bodyParser = require("body-parser");
import path = require("path");
import compression = require("compression");
import router = require("./router");

var app = express();
var port = process.env.PORT || 5000;
var projectRoot = path.join(__dirname, "..");
var clientRoot = path.join(projectRoot, "Client");

app.use(compression());

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: true
}));

app.use(express.static(clientRoot));

app.use(function (req, res, next) {
    res.locals.clientRoot = clientRoot;
    next();
});

app.use("/", router);

app.listen(port, err => {
    console.log(`running server on port ${port}`);
});

```

The Content-Encoding header is still application/javascript

![image](https://cloud.githubusercontent.com/assets/1405648/19997307/73519714-a2a0-11e6-9903-aee123ddea80.png)

and the file does not seem to be compressed

![image](https://cloud.githubusercontent.com/assets/1405648/19997335/ba4c58de-a2a0-11e6-9846-979325769d46.png)

I have tried to restart my browser, run express server with NODE_ENV=production but still do not help

I also tried add filter:

```
import express = require("express");
import bodyParser = require("body-parser");
import path = require("path");
import compression = require("compression");
var compressible = require('compressible')
import router = require("./router");

var app = express();
var port = process.env.PORT || 5000;
var projectRoot = path.join(__dirname, "..");
var clientRoot = path.join(projectRoot, "Client");

function shouldCompress(req: express.Request, res: express.Response) {
    var type = res.get("Content-Type");

    if (type === undefined || !compressible(type)) {
        return false
    }
    console.log('should compress: ', req.originalUrl)
    return true
}

app.use(compression({filter: shouldCompress}));

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: true
}));

app.use(express.static(clientRoot));

app.use(function (req, res, next) {
    res.locals.clientRoot = clientRoot;
    next();
});

app.use("/", router);

app.listen(port, err => {
    console.log(`running server on port ${port}`);
});
```

Even though the console prints:
![image](https://cloud.githubusercontent.com/assets/1405648/19997580/81687870-a2a2-11e6-994e-e5176d245d9e.png)
no file is compressed

I am using express 4.14.0 with compression 1.6.2 and node 4.4.7

**Comment by dougwilson** [comment]
I tried your app and it compressed just fine for me, so I'm not sure. We seem to get this issue opened regularly and it always ends the same: Chrome/Firefox are not showing it compressed for some reason yet this module is writing it compressed to the socket.  Using Fiddler usually reveals that indeed, it is compressed from the Node.js server: https://github.com/expressjs/compression/issues/96#issuecomment-257515673

Can you try validating with the Fiddler tool?

**Comment by KathyDinh** [comment]
Thank you for your prompt response.
I tried your suggestion with Fiddler 4.
Still, there is no compression no matter which browser I use: Chrome, FF, IE.

**Comment by dougwilson** [comment]
Weird, because when I use your app, I see the compression. I'm' unsure what the difference is. I used Node.js 4.4.1 just as you reported, and Express 4.14.0 and compression 1.6.2.

**Comment by KathyDinh** [comment]
I created a much simpler project with a 129KB json file and enable debug
![image](https://cloud.githubusercontent.com/assets/1405648/20011892/191a63d2-a2e8-11e6-967a-7d8eea069909.png)
According to printed msg, compression happened.
However, neither browser nor Fiddler show that the file is compressed.
Truly strange

**Comment by dougwilson** [comment]
Hm. Are we sure there is not a process on that computer intercepting HTTP traffic and silently decompressing it? Would trying it on a different machine be possible? If not, what about using Wireshark and capturing the packets being emitted from the Node.js process to see if they are compressed?

**Comment by yannik-b** [comment]
Maybe Chrome has the old version without compression cached.

Try `Ctrl`+`Shift`+`R` to load the new version. That was my mistake too.

**Comment by dougwilson** [comment]
Without any reliable way to reproduce, and no responses to my questions, I'm not sure this issue is going to progress any further. If you ever track down the reason, please let us know what it is, maybe there is something we can fix.
