### ISSUE TITLE
Compression for woff2 file?

### ISSUE THREAD

**Issue by yannik-b** [expressjs/compression#99]
Is it possible that a woff2 font file can't be compressed?
All my files (static files too) are compressed but not the fontAwesome.woff2

**Comment by jonathanong** [comment]
https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a#good-to-know 

i'm not sure how good that source is, but i recall the same statement from a while ago - woff files are basically already compressed

**Comment by yannik-b** [comment]
Ah okay. Thanks :)
